services:
  app:
    container_name: theshawnshop_app
    build:
      context: .
      dockerfile: Dockerfile
    image: theshawnshop
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      DOTNET_EnableWriteXorExecute: 0
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_REVALIDATE_FREQ: 2
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 32531
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 64
      PHP_OPCACHE_MEMORY_CONSUMPTION: 512
      PHP_FPM_POOL_NAME: "theshawnshop_php"
    #   SSL_MODE: "mixed"
    #   SSL_PRIVATE_KEY_FILE: "/etc/ssl/private/sreportal.test-key.pem"
    #   SSL_CERTIFICATE_FILE: "/etc/ssl/private/sreportal.test.pem"
    volumes:
      - ".:/var/www/html/"
    #   - "./opt/certs/:/etc/ssl/private/"
    networks:
      - theshawnshop_app
    depends_on:
      - mssql
      - redis

  vite:
    container_name: theshawnshop_vite
    image: node:22-bookworm
    environment:
      NODE_ENV: local
    working_dir: /var/www/html
    command: npm run dev
    volumes:
      - .:/var/www/html:cached
    ports:
      - "5173:5173"
    networks:
      - theshawnshop_app
    depends_on:
      - app
  mssql:
    container_name: theshawnshop_mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - theshawnshop_mssql_data:/var/opt/mssql
    networks:
      - theshawnshop_app

  redis:
    container_name: theshawnshop_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - theshawnshop_app
    volumes:
        - theshawnshop_redis_data:/data

#   horizon:
#     container_name: gourmand_horizon
#     image: gourmand
#     working_dir: /var/www/html/
#     command: php artisan horizon
#     volumes:
#       - ".:/var/www/html/"
#     networks:
#       - gourmand_app
#     depends_on:
#       # - pgsql
#       - mssql
#       - redis
#       - app
#     restart: unless-stopped

networks:
  theshawnshop_app:
    driver: bridge

volumes:
  theshawnshop_mssql_data:
  theshawnshop_redis_data:
