deployment:
  replicas: 1
  image:
    repository: shawnweigand/prod
    tag: shawnshop
  probes:
    enabled: false
  registry:
    imagePullSecret: docker-registry-secret

serviceAccount:
  name: docker-registry-serviceaccount
  imagePullSecret: docker-registry-secret

ingress:
  host: theshawnshop.com
  tls: true
  externalPort: 80
  internalPort: 8080

issuer:
  email: weigandshawn@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory

pdb:
  minAvailable: 1

horizon:
  enabled: false
  replicas: 1

redis:
  enabled: true

config:
  APP_NAME: "The Shawn Shop"
  VITE_APP_NAME: "The Shawn Shop"
  APP_URL: https://theshawnshop.com
  APP_ENV: production
  DB_CONNECTION: sqlsrv
  DB_PORT: 1433
  DB_TRUST_SERVER_CERTIFICATE: true
  MAIL_MAILER: mailgun
  MAILGUN_DOMAIN: theshawnshop.com
  WORKOS_REDIRECT_URL: https://theshawnshop.com/authenticate
  SESSION_DRIVER: redis
  QUEUE_CONNECTION: redis
  CACHE_STORE: redis
  REDIS_CLIENT: phpredis
  REDIS_HOST: shawnshop-redis
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

